const variable = "findMyHipHop";
const scope = "dcat23"
const website = "dcat.tech"
const fileName = "find-my-hip-hop"
const className = "FindMyHipHop"
const propertyName = "findMyHipHop"
const constantName = "FIND_MY_HIP_HOP"
const snakeCaseName = "find_my_hip_hop"
const title = "Find My Hip Hop"
